name: WinterSlash2.0
main: me.i3ick.winterslash.WinterSlashMain
version: 1.8
description: WinterSlash game
commands: 
  ws: 
    description: "Main WinterSlash command"

permissions: 
  winterslash.*: 
    description: "Gain access to all freezetag commands!"
    children: 
      winterslash.leave: true
      winterslash.join: true
      winterslash.list: true
      winterslash.pn: true
      winterslash.remove: true
      winterslash.setred: true
      winterslash.setgreen: true
      winterslash.signplace: true
      winterslash.create: true
      winterslash.setlobby: true
    default: op
  winterslashplayers.*: 
    description: "Give normal players permission to play Freezetag!"
    children: 
      winterslash.leave: true
      winterslash.join: true
      winterslash.list: true
    default: player